spring:
  datasource:   #多数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    master:
      url: jdbc:mysql://192.168.28.108:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: systec
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      url: jdbc:mysql://192.168.29.54:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: systec
      driver-class-name: com.mysql.jdbc.Driver

    druid:
      initial-size: 5
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy


#spring:
#  datasource:   #多数据源配置
#    type: com.alibaba.druid.pool.DruidDataSource
##    url: jdbc:mysql://localhost:3307/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false
#    url: jdbc:mysql://localhost:3308/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver


#  jpa:
#    show-sql: true

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.imooc.entity
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    default-executor-type: reuse
#    default-statement-timeout: 600




